### ISSUE TITLE
Option to exclude bots

### ISSUE THREAD

**Issue by RCheesley** [SavannahHQ/Savannah#2]
It would be super helpful if it was possible to have a select field on the user profile to identify if it was a bot, and therefore excluded from any of the metrics. 

Travisbuddy tells everybody that it would be awesome if they fix their PR, which is showing as positive sentiment!

**Comment by mhall119** [comment]
This raises a kind of philosophical question, is the bot part of your community? It's interacting with members, and it's text does impact the overall sentiment of conversations. Is there insight to be gained from seeing the bot's activity alongside human activity in your community?

**Comment by mhall119** [comment]
I've been planning on adding a flag to distinguish Members between staff and external community, perhaps extending this to allow flagging as a bot as well would be the right approach.  

I'm not convinced that excluding it from the metrics is the right way to go, but being able to differentiate it within the metrics makes sense

**Comment by RCheesley** [comment]
That might be a good workaround, allowing an option to flag staff and bots and use that to filter if desired.

**Comment by mhall119** [comment]
This is resolved with the introduction of the `Roles` filter
